### ISSUE TITLE
コメントの非同期で削除する方法が実装出来ません

### ISSUE THREAD

**Issue by HirotakaSaitoh** [HirotakaSaitoh/muscle#5]
トップページで動画に対するコメントを非同期で削除しようとしたのですが、
DBテーブルの対応するカラムは削除出来たのですが、HTML上のコメントが削除ボタンを押したときに同時に消えません。 スクリプトのclear_id.removeChild(p_id);でコメントを消そうと思ったのですが、エラーが出てしまいます。（エラー内容Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.）
お忙しいところ申し訳ありませんが、アドバイス頂けると助かります。
宜しくお願い致します。

           <div id="comment">
            @foreach ($commentUser as $cu) 
                <div id = "comment_clear" name='{{ $cu -> id}}'>
                    
                    <p id="{{ $cu -> id}}"><b>{{ $cu -> name}}</b>  <i class="far fa-comments"></i> {{ $cu -> movie_comment}}
                    <input type="button" id="clear" name='{{ $cu -> id}}'  value="削除筋" class="btn btn-warning btn-sm" >
                    </p>
                
                </div>
            @endforeach    
           </div>

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

    window.addEventListener('load', function(){    
        var clearElement = document.getElementById("clear");
        clearElement.onclick = function (){
                
                var deleteConfirm = confirm('その削除、筋肉量を2g失うが大丈夫でしょうか？');
                
                if(deleteConfirm == true){
                      
                    var clearElement = document.getElementById("clear"); 
                  　var c_id = clearElement.getAttribute('name');
                    var formdata_delete = new FormData();
                        formdata_delete.append('id', c_id);  
                    
                    //非同期の削除処理をする
                    var xhr = new XMLHttpRequest();
                    
                    var token3 = document.getElementsByName('csrf-token3').item(0).content; 
                    
                    var clear_id = document.getElementById("comment_clear");
                    var p_id = document.getElementById("{{ $cu -> id}}");
                    //　var c_id2 = clearElement2.getAttribute("id");
                    clear_id.removeChild(p_id);

                    xhr.open('POST', "movie/comment_delete", true);
                    xhr.setRequestHeader('X-CSRF-Token', token3); 
                    xhr.send(formdata_delete);

                }else{
                    //error処理を書く
                }
        };
    })

**Comment by zprodev** [comment]
@HirotakaSaitoh 
いくつか実装上の問題があるので、まずその辺を見直してみてください 👍 

 - foreachで`id = "comment_clear"`の要素を複数作っている（同じページ内に同じidを持つ要素を複数作ってはいけない）
 - `var p_id = document.getElementById("{{ $cu -> id}}");`の$cuはコントローラーで定義したものでは無い（foreachの中で作ったものなのでここでは使えません）

**Comment by HirotakaSaitoh** [comment]
ご指摘ありがとうございます！

ユーザーコメントを非同期で削除するにあたり、各コメントに個別のid等を持たせるためにforeachの$cuを使っておりました。foreachでできる各コメントが個別のidをもってそれをjavascriptで扱うにはどのような方法がありますでしょうか？
参考になるページ等ありましたら教えて頂けると嬉しいです。

宜しくお願いします！

**Comment by zprodev** [comment]
HTMLのボタン要素押下時にJavascriptの関数を実行する書き方ができます。
https://www.ipentec.com/document/javascript-exec-javascript-on-button-click

↓はボタン押下時にid=1としてhoge関数を実行する例です。
```
<script>
function hoge(id){
}
</script>
<input type="button" value="ボタン" onclick="hoge(1);"/>
```

**Comment by kazosan** [comment]
ありがとうございます！
