### ISSUE TITLE
blade.phpのスクリプト内にて{{変数}} がコメントアウトしてもif文で条件から外しても参照されてしまう件

### ISSUE THREAD

**Issue by HirotakaSaitoh** [HirotakaSaitoh/muscle#6]
top.blade.phpのスクリプト内にて{{変数}} がコメントアウトしてもif文で条件から外しても参照されてしまいます。どのようにしたら{{変数}}が参照されないようになるか教えて頂きたいです。宜しくお願い致します。

**Comment by zprodev** [comment]
@HirotakaSaitoh 
記述を削除しても問題が出ますか？
問題が出ないなら、コメントアウトの書き方が間違っているんじゃ無いかと思います。

**Comment by HirotakaSaitoh** [comment]
記事を削除する場合は問題無いです。ですが、if else 文で条件外の場合でも①下記の様な記述が読み込まれてしまい、if else 文で条件外の場合に読み込まれないように実装したいです。宜しくお願い致します。(ちなみにコメントアウトは②の様に記述しています。
)

①var p_id = document.getElementById("{{ $cu -> id}}");
②// var p_id = document.getElementById("{{ $cu -> id}}");

**Comment by zprodev** [comment]
「参照されてしまいます」というのはLaravelの`return view();`実行ででエラーが出るとかって事でよいですかね？

であれば、
// var p_id = document.getElementById("{{ $cu -> id}}");
はJavaScript実行時に無視させるためのコメントアウト方法なので、
Laravelの解析時に無視させるようコメントアウトする必要があると思います。

Bladeのコメント方法を見ると（https://readouble.com/laravel/5.5/ja/blade.html）
{{-- var p_id = document.getElementById("{{ $cu -> id}}"); --}}
って感じじゃないですかね？

**Comment by kazosan** [comment]
ありがとうございます！
