### ISSUE TITLE
cloud9からさくらサーバーへのlaravel移管がうまくいきません

### ISSUE THREAD

**Issue by HirotakaSaitoh** [HirotakaSaitoh/muscle#8]
laravelのバージョンは5.5.48でさくらサーバーでも同じバージョンをインストールしたつもりです。laravelの中のファイルも全部同じなはずなのですが、以下のエラーメッセージが出てしまいます。(laravelのバージョンを確認しても同じエラーが出て確認することが出来ません。)色々とググってみたのですが、対処法が分からず困っております。

  'prefix' => env(
        'CACHE_PREFIX',
        str_slug(env('APP_NAME', 'laravel'), '_').'_cache'
    ),

エラーメッセージ
"Call to undefined function str_slug()"

**Comment by zprodev** [comment]
@HirotakaSaitoh 
このサイトは参考になりませんかね？
https://blog.e2info.co.jp/2019/09/21/laravel6-call-to-undefined-function-str-slug/

**Comment by HirotakaSaitoh** [comment]
アドバイスありがとうございます。
Strのクラスを定義して、laravel5.5の書き方に変更したらエラー解消されました。ありがとうございました。ただ、さくらサーバーにしたことで数か所でエラーが出てしまっているかもしれません。
